---

- name: restart networkd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  with_items:
  - systemd-networkd
  - systemd-resolved
  - systemd-timesyncd
